name = "zero2pm-reactions"
main = "worker.js"
compatibility_date = "2024-09-01"

# 1. Create KV namespace:
#    wrangler kv:namespace create REACTIONS
# 2. Paste the returned id below:
[[kv_namespaces]]
binding = "REACTIONS"
id = ""          # <-- fill in after step 1
